return {
	-- "yetone/avante.nvim",
	-- event = "VeryLazy",
	-- lazy = false,
	-- version = false,
	-- opts = {
	-- 	-- Use copilot as the provider
	-- 	provider = "copilot",
	-- 	auto_suggestions_provider = "copilot",
	--
	-- 	-- New provider configuration format
	-- 	providers = {
	-- 		copilot = {
	-- 			endpoint = "https://api.business.githubcopilot.com",
	-- 			model = "gpt-4o-2024-05-13",
	-- 			timeout = 30000,
	-- 			allow_insecure = true, -- Windows SSL fix
	-- 			extra_request_body = {
	-- 				temperature = 0,
	-- 				max_tokens = 4096,
	-- 			},
	-- 		},
	-- 	},
	--
	-- 	-- Behaviour settings
	-- 	behaviour = {
	-- 		auto_suggestions = false,
	-- 		auto_set_highlight_group = true,
	-- 		auto_set_keymaps = true,
	-- 		auto_apply_diff_after_generation = false,
	-- 		support_paste_from_clipboard = false,
	-- 	},
	--
	-- 	-- UI settings
	-- 	mappings = {
	-- 		diff = {
	-- 			ours = "co",
	-- 			theirs = "ct",
	-- 			all_theirs = "ca",
	-- 			both = "cb",
	-- 			cursor = "cc",
	-- 			next = "]x",
	-- 			prev = "[x",
	-- 		},
	-- 		suggestion = {
	-- 			accept = "<M-l>",
	-- 			next = "<M-]>",
	-- 			prev = "<M-[>",
	-- 			dismiss = "<C-]>",
	-- 		},
	-- 		jump = {
	-- 			next = "]]",
	-- 			prev = "[[",
	-- 		},
	-- 		submit = {
	-- 			normal = "<CR>",
	-- 			insert = "<C-s>",
	-- 		},
	-- 	},
	--
	-- 	windows = {
	-- 		position = "right",
	-- 		wrap = true,
	-- 		width = 30,
	-- 		sidebar_header = {
	-- 			align = "center",
	-- 			rounded = true,
	-- 		},
	-- 	},
	--
	-- 	highlights = {
	-- 		diff = {
	-- 			current = "DiffText",
	-- 			incoming = "DiffAdd",
	-- 		},
	-- 	},
	--
	-- 	diff = {
	-- 		autojump = true,
	-- 		list_opener = "copen",
	-- 	},
	-- },
	--
	-- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false",
	--
	-- dependencies = {
	-- 	"nvim-treesitter/nvim-treesitter",
	-- 	"stevearc/dressing.nvim",
	-- 	"nvim-lua/plenary.nvim",
	-- 	"MunifTanjim/nui.nvim",
	-- 	"nvim-tree/nvim-web-devicons",
	-- 	{
	-- 		"zbirenbaum/copilot.lua",
	-- 		opts = {
	-- 			suggestion = { enabled = false },
	-- 			panel = { enabled = false },
	-- 			-- Force enterprise authentication
	-- 			server_opts_overrides = {
	-- 				settings = {
	-- 					advanced = {
	-- 						inlineSuggestCount = 3,
	-- 					},
	-- 				},
	-- 			},
	-- 		},
	-- 	},
	-- 	{
	-- 		"HakonHarnes/img-clip.nvim",
	-- 		event = "VeryLazy",
	-- 		opts = {
	-- 			default = {
	-- 				embed_image_as_base64 = false,
	-- 				prompt_for_file_name = false,
	-- 				drag_and_drop = {
	-- 					insert_mode = true,
	-- 				},
	-- 				use_absolute_path = true,
	-- 			},
	-- 		},
	-- 	},
	-- 	{
	-- 		"MeanderingProgrammer/render-markdown.nvim",
	-- 		opts = {
	-- 			file_types = { "markdown", "Avante" },
	-- 		},
	-- 		ft = { "markdown", "Avante" },
	-- 	},
	-- },
	--
	-- keys = {
	-- 	{ "<leader>av", "<cmd>AvanteToggle<cr>", desc = "Toggle Avante", mode = { "n", "v" } },
	-- 	{ "<leader>aa", "<cmd>AvanteAsk<cr>", desc = "Ask Avante", mode = { "n", "v" } },
	-- 	{ "<leader>ar", "<cmd>AvanteRefresh<cr>", desc = "Refresh Avante", mode = "n" },
	-- 	{ "<leader>ae", "<cmd>AvanteEdit<cr>", desc = "Edit with Avante", mode = "v" },
	-- },
}
