-- return {
--   "rcarriga/nvim-notify",
--   dependencies = { "nvim-tree/nvim-web-devicons" },
--   config = function()
--     require("notify").setup()
--     vim.notify = require("notify")
--   end,
-- }
